#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b

if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "#282828"
bspc config focused_border_color  "#81A1C1"
bspc config presel_feedback_color "#88C0D0"

#bspc rule -a Gimp desktop='^4' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
