#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b

if [[ $HOSTNAME == hsuse ]] then
    bspc monitor rdp0 -d 1 2 3 4
    bspc monitor rdp1 -d 5 6 7 8
else
    bspc monitor DisplayPort-0 -d 1 2 3 4
    bspc monitor HDMI-A-0 -d 5 6 7 8
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "#282828"
bspc config focused_border_color  "#81A1C1"
bspc config presel_feedback_color "#88C0D0"

#bspc rule -a Gimp desktop='^4' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
