#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b
pgrep -x fcitx > /dev/null || fcitx

if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d 1 2 3 4 5 
  bspc monitor $(bspc query -M | sed -n 2p) -d 6 7 8 9 
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9
fi


bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.65
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "#282828"
bspc config focused_border_color  "#D5C4A1"
bspc config presel_feedback_color "#88C0D0"

#bspc rule -a Gimp desktop='^4' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
